### ISSUE TITLE
Weird player bouncy bug.

### ISSUE THREAD

**Issue by Puk4400** [YePpHa/YouTubeCenter#1497]
Hello. I stumbled upon a very unpleasing issue. 

Current version and settings: v488, default settings except "grid subscription" unchecked; "prevent auto-play" checked; "auto-resolution 1440p" and "player size" at 70%. I tried older versions too, same issue.

Issue: Playing a video with HTML5 is causing the player to bounce up and down constantly, even after paused. More like, the video itself starts bouncing inside the player and the player bar disappears while the video is bouncing down and appears when the video moves back inside the player.
It's a bit tough to explain. I suppose this is caused by the video bar since on flash i don't have this issue and the bar goes down completely on playback while on HTML5 it stays visible all the time.

I installed v488 today and i played videos perfectly fine with no problems, but suddenly this started to happen and even changing versions doesn't do anything. I didn't change any of the settings. The issue started out of nowhere.

**Comment by JonET** [comment]
Same here. Making me a little sick.

**Comment by Puk4400** [comment]
I can quickly fix it by playing with flash, but flash tends to get laggy those days and HTML5 currently has almost the same picture quality with consistent FPS and an overall smoother experience than flash. At least for me, so this issue is bugging me a little.

**Comment by Zarggg** [comment]
Reporting this issue as well. It only seems to happen when returning *from* full-screen view. Bouncing does continue even if the video is paused.

Debug Log: https://gist.github.com/38a32e60c2aab2596b5d

**Comment by Puk4400** [comment]
For me it happens regardless if i go to fullscreen or not.

**Comment by deathdragon1987** [comment]
Yep Made a gif of it http://i.imgur.com/MWIVpIz.gif

**Comment by RSully** [comment]
I noticed this happening this morning both before and after updating the extension. Running Safari, HTML5.

**Comment by Mrucux7** [comment]
Had this too, switching to Auto-hide bar to Both seems to have fixed it.

**Comment by Blackbird88** [comment]
Getting this too.

**Comment by Puk4400** [comment]
Better, change "auto-hide bar" to "only controlbar" fixes it and it's back to how HTML5 was before.
That should explain what caused the issue, the video bar is the culprit. I see youtube made some changes around and mostly likely those interfered with the extension code.

**Comment by Puk4400** [comment]
Thanks Mrucux7 for the suggestion.

**Comment by not4u2kno** [comment]
Flicker of nausea here too... Seemed to happen to the version before 488 also. Changing "Player > Auto hide bar > Both Progressbar & Controlbar" returned it back to normal functionality.

I suspect YT's changes to be the cause. Ever since I've seen the new 'Autoplay' and countdown crap on video ending it started happening.

**Comment by Zarggg** [comment]
Confirming fixes suggested by @Mrucux7, @Puk4400, and @not4u2kno for Firefox 36b10 using HTML5 player. This seems to be caused by a recent YouTube change that went live today.

**Comment by BradJJ** [comment]
Boing Boing Boing Boing Boing Boing Boing 

thanks for the quick fix dudes.

**Comment by SnowGabe** [comment]
Happens also here with the dev build. Google Chrome 40.0.2214.115 m (64-bit).

**Comment by DefilAStar** [comment]
same Problem here, using Chrome Version 42.0.2311.4 dev-m & Youtube Center dev build 488

**Comment by Turbonator** [comment]
This bug has been alive earlier also, around a week ago it only affected the channel background which keeps stuttering and bouncing. Now also player bar is affected.

**Comment by YePpHa** [comment]
It's most likely fixed in the latest developer version. It seems like the class `ideal-aspect` was added and removed by YouTube constantly, which caused it to switch between two different auto-hide modes. The fix should make sure that the two modes are the same, which will hopefully fix the 'bouncing'.

**Comment by Turbonator** [comment]
Fixed.

**Comment by Zarggg** [comment]
Confirmed fixed in Firefox (37b1) and "Auto-hide behavior" set to Default.

**Comment by Mrucux7** [comment]
Fixed on Canary 43.0.2313.0 and default setting for auto-hide bar.

**Comment by Puk4400** [comment]
Chrome Version 40.0.2214.115 m & dev-center v489 issue fixed.
Thank you.

**Comment by Turbonator** [comment]
Only controlbar has bouncing issue still, and when selecting Default it hides both bars.

**Comment by Djfe** [comment]
@YePpHa this is not completely fixed!!!
works for the default case but if you set the setting so that you want to hide only the control bar it will bounce again

the settings "both", "none" and "only loading bar" work just fine though (thx for the partail fix)

**Comment by Turbonator** [comment]
@Djfe But Default hides both, so Default is not fixed completely either

**Comment by Puk4400** [comment]
I'll reopen since users reported new issues.

**Comment by Puk4400** [comment]
Confirmed, auto-hide bar set to either progressbar or controlbar is still causing the same issue. 
Dev-center v489.

**Comment by Sollace** [comment]
I'm still having problems with this although it only happens when the page loads with the player expanded.

I've found this happens on:
- Default
- Only Controlbar
- Only Progressbar

It stops if you switch between the options but will just come back the next time you load the page. Sometimes it only starts after you've interacted with the player (pause and unpause).

YTC version: Dev Build #492
Browser: Mozilla Firefox 35.0.1
Addon type: Userscript

**Comment by jcink** [comment]
Yeah I am still having problems with this as well and you are correct, it only happens with the expanded player on build 492.

**Comment by xur86x** [comment]
Just wanted to bump this, because it's still not working with Firefox 36.0.1 and the latest developer build (492).

**Comment by Hubcapp** [comment]
Here it is, still a problem in 492.

http://imgur.com/8S3zDrp

**Comment by xur86x** [comment]
I'm using build 495 on Firefox 36 and it seems to be fixed.

**Comment by jcink** [comment]
Build 495 on firefox 36.0.4 and still not fixed for me. :(

**Comment by xur86x** [comment]
This is interesting. What OS are you using?

**Comment by Djfe** [comment]
Happened to me just now before the page was fully loaded (hovering the bar resulted in bouncing), I'm using the current dev version and FF 37

after the page was fully loaded the bouncing was gone

my setting is still: only autohide progressbar

**Comment by SnowGabe** [comment]
Started to happen again after the dev build 499.

**Comment by kptkill** [comment]
Developer Build 503 has this problem w/ HTML5 playback
