### ISSUE TITLE
[Bug] After video playback ends spacebar activates video in comment section instead of adding spaces in comments.

### ISSUE THREAD

**Issue by Corruptinglyneedful** [YePpHa/YouTubeCenter#1631]
gettrtingreallysickofthisytcbug

**Comment by LaVey-Charkus-Veros** [comment]
I know. This happened to me too a few days ago but now I don't have this problem anymore. It was extremely annoying, though, trying to write a comment and see the video starting to play every time, no matter where you clicked the mouse on the page to free it from the player.

**Comment by q1k** [comment]
I thought this was fixed in the developer version
btw, I never had this problem.

**Comment by Zarggg** [comment]
Please start searching the issues before reporting them. This one has been reported many times. A workaround has also been posted more than once.

**Comment by Corruptinglyneedful** [comment]
@Zarggg Where is this work-around?  Work-around or not, it STILL needs fixed.  It was supposed to have been fixed but it still exists.

**Comment by Zarggg** [comment]
As mentioned in #1546 and #1577, disable the "Enable shortcuts on page" setting.

Even if you search just *space bar* on the repo, three of the first five Issues listed are related to this.

**Comment by Corruptinglyneedful** [comment]
@Zarggg If I disabled that shortcut, won't that mean that it stops me from pausing the video with spacebar?

**Comment by Zarggg** [comment]
No.Read this: https://github.com/YePpHa/YouTubeCenter/wiki/Features#Enable_Shortcuts_on_Page

**Comment by Corruptinglyneedful** [comment]
I see, thank you.

Also, be nicer, no need to be rude.  You were ruder earlier.
