### ISSUE TITLE
Youtube player just updated, seems to broke a few things

### ISSUE THREAD

**Issue by viion** [YePpHa/YouTubeCenter#1633]
If you have an old dev version then need to update now as the new icons wont show. Also the player seems to fix its size? (or new css names, eg: ytp-chrome-bottom). Eg this is 80% setting

http://i.imgur.com/qUIITQC.jpg

**Comment by Yonezpt** [comment]
Your english is a bit hard to understand, but the picture is not. That issue is fixed in the latest developer version 497, if you aren't using it already then you can download it from here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by viion** [comment]
I downloaded the latest developer version. (I was previously on an older developer version due to the speed developer version updates). 

On version 497 the player is still broken, it simply does not resize past the original, this is with 80%:

Im on Mac/Chrome, if it helps.

http://i.imgur.com/0mWjo9o.png

**Comment by Yonezpt** [comment]
The platform shouldn't matter, but the browser does. I have also tested it with Chrome and it is still working correctly, the player is resizing as it should.

Are you using the userscript version?

Try reseting YTC settings to default, check if the issue is fixed.

If it isn't then try disabling any other extensions you have running except YTC, check again if the issue is fixed.

If the issue still persists then press F12 and type the following: `ytplayer.config.assets.js`

Press enter and share here the link it returns. I will test the HTML5 player you are being offered and see where the problem lies if I can reproduce the issue.

**Comment by viion** [comment]
Tried both userscript and crx, both from scratch (deleted old extention, dragged on newly downloaded one one). Disabling all other extensions has no change.

This is with a fresh - default settings of Youtube center (both js and crx) http://i.imgur.com/re9FQFH.png - you can see the right side buttons are missing, and the video is too large for the actual player. I can tweak it in dev tools to fix by reducing the size.

```
ytplayer.config.assets.js
> //s.ytimg.com/yts/jsbin/html5player-new-vfl-WQS6x/html5player-new.js
```

**Comment by Yonezpt** [comment]
That's the first time I have seen the html5 player being shipped with the link containing "-new". Thanks for the share, will study it and see what I can do.

**Comment by viion** [comment]
I logged out and I get the old player, a colleague also has the old player. Maybe I'm one of the lucky ones (or unlucky in this case, i want my huge 80% player!).

If there anything i can provide to help on this I will. Though I suspect it might get updated again as the aspect ratio is all messed up with huge gaps on videos.

**Comment by Yonezpt** [comment]
No, what I think it happened is that you were served with the new YouTube player that has transparent controls which YouTube has been testing in secret for the past month and I have been trying to hunt it down ever since it was first reported so that I can see what is causing the issue. Thanks to you I was finally able to get the link for it.

You now don't have it because when you logged out you lost the cookie that was responsible for that experiment, so now you are being served with the standard player which resizes correctly with YTC.

Could you just do one favor and change the title to "YouTube transparent player doesn't resize properly"? This way we will be able to differentiate this type of issue from the standard player.

**Comment by viion** [comment]
Updated title, you're right about everything. At home I do not get this (when logged in my account), only at my work PC do i get this player. I will keep it active in chrome incase anything else is required for this issue.

**Comment by Yonezpt** [comment]
If you are still getting the transparent player in your work PC could you share with me more details? It seems like the player needs more things to run properly.

Like before press F12 and open the Console tab, type the following: `JSON.stringify(ytplayer.config.assets)`

Press enter and share returned text

Type the following: `document.querySelectorAll('script[name]')`

Press enter and share the returned information

**Comment by viion** [comment]
Saw your email, don't know if you need.

``` 
> JSON.stringify(ytplayer.config.assets)
"{"js":"//s.ytimg.com/yts/jsbin/html5player-new-vfl-WQS6x/html5player-new.js","css":"//s.ytimg.com/yts/cssbin/www-player-new-webp-vfl39N14y.css"}" 
```

```
document.querySelectorAll('script[name]')
[<script src="//s.ytimg.com/yts/jsbin/www-scheduler-vflciesgc/www-scheduler.js" type="text/javascript" name="www-scheduler/www-scheduler" class="js-httpssytimgcomytsjsbinwwwschedulervflciesgcwwwschedulerjs"></script>, 
<script src="//s.ytimg.com/yts/jsbin/html5player-new-vfl-WQS6x/html5player-new.js" type="text/javascript" name="html5player/html5player" class="js-httpssytimgcomytsjsbinhtml5playernewvflWQS6xhtml5playernewjs"></script>,
<script src="//s.ytimg.com/yts/jsbin/spf-vflQul50b/spf.js" type="text/javascript" name="spf/spf" class="js-httpssytimgcomytsjsbinspfvflQul50bspfjs"></script> ,
<script src="//s.ytimg.com/yts/jsbin/www-en_US-vflAhK8Xk/base.js" name="www/base" class="js-httpssytimgcomytsjsbinwwwen_USvflAhK8Xkbasejs"></script> ]
YouTubeCenter.js:2022 YouTube configuration data is inaccessible; giving up on language auto-detection.

```

**Comment by Yonezpt** [comment]
@viion Thanks, but I eventually managed to get the other necessary file which was the CSS stylesheet containing the transparent player layout. Without it the player was giving me problems.

**Comment by apat183** [comment]
I'm also getting this issue with mostly default settings, I get the issue only though when I set the player type to HTML5/default, its fine on flash. I'm also on a mac and using chrome 41.

http://i.imgur.com/aB79jvr.png

**Comment by Yonezpt** [comment]
@apat183 Your issue is not the same as this issue, you don't have the new transparent player. But you can try installing the developer version which I suspect might be your problem, you can find it here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by apat183** [comment]
@Yonezpt your right, the developer version fixed it. Thanks
