### ISSUE TITLE
Lights out leaves massive void below video

### ISSUE THREAD

**Issue by Ghosthree3** [YePpHa/YouTubeCenter#1708]
Still happening in B502

**Comment by brandon8** [comment]
I'm also having this issue. And I'm using the developer version 502

**Comment by caeldom** [comment]
Confirmed in b502, using Chrome v42.0.2311.90 m

Was trying to change every other setting to work out what was causing that void! Thankfully I check the issues list. Note: toggling lights on/off will also toggle the void appearing.

**Comment by Ghosthree3** [comment]
Fixed in 503

**Comment by caeldom** [comment]
Unfortunately still occurs for me in 503 :/ Chrome updated to v42.0.2311.135 m

Furthermore, a small space has appeared between the header and video which wasn't previously there.

![image](https://cloud.githubusercontent.com/assets/6067646/7414752/012ae8be-ef98-11e4-97a4-8f1dc634ce79.png)

**Comment by Piter432** [comment]
@caeldom This small space is good, because I always thinking that video is slightly "cutted" by this header.

**Comment by LiamBM** [comment]
They should keep the small Gap. Makes the page look neater.

**Comment by Ghosthree3** [comment]
I do prefer the space as well.

**Comment by caeldom** [comment]
I have the header auto-hide so the gap becomes quite redundant without the header. Perhaps, if the hide header option is enabled, then the gap should be removed? or at the least, shortened to maybe one or two pixels?

**Comment by Ghosthree3** [comment]
Actually it is still happening, I guess it's random.

**Comment by caeldom** [comment]
Fixed in dev507!
