### ISSUE TITLE
Counterintuitive behavior for 'Enable annotations'

### ISSUE THREAD

**Issue by Starfox** [YePpHa/YouTubeCenter#2172]
So the options is checkbox called "Enable annotations"

When the checkbox is checked it turns OFF annotations in videos by default
When the checkbox is unchecked it turns ON annotations in videos by default

So 'Enable annotations' turns OFF annotations when it is turned ON, is that counterintuitive to anyone else?

**Comment by andyb2** [comment]
On or off it doesn't do anything for me they are always on

**Comment by Starfox** [comment]
Yea or that, disabling annotations is just plain broken in youtubecenter

**Comment by CathalCraft** [comment]
For me on Chrome, I have Enable Annotations unchecked and they are still enabled for videos that have annotations. This is very annoying as I have to disable annotations for every video that I watch.

**Comment by grocal** [comment]
It's worth noting that this annotations problem is only for HTML5 player. If user switches to flash player (we talk about Chrome browser) then show/hide annotations checkbox turns on/off annotations correctly.

**Comment by grocal** [comment]
It's me again. I'm using Build#538 on Chrome with Tampermonkey and I've fixed annotations problem. It turns out that disable/enable annotations checkbox shows up in **three different places**! It should be turned off at all of them. It's:

- Player -> General -> Enable annotations
- External players -> Embed -> Enable annotations
- External players -> Channel -> Enable annotations

Only then annotations won't show up in HTML5 player for Chrome/Tampermonkey/Build#538

**Comment by andyb2** [comment]
I know there is 3 places and they have always been unchecked  yet still get them

**Comment by RaviOnline** [comment]
Yes, this functionality is broken in YTC but YouTube lets us control annotations too. Go to _Account Settings > Playback_ and uncheck _Show annotations and in-video notifications_.

I actually wish that YTC pulls this setting out to the YouTube bar itself, right next to _Closed Captions_, as I often feel the need to enable them just for the video I'm watching and going through the menu is slow. The video often ends by the time I enable it.
