### ISSUE TITLE
playlist crunches

### ISSUE THREAD

**Issue by YouTubeEdge** [YePpHa/YouTubeCenter#2339]
When playing a playlist it will show as believed it normally should for a second and then seems to "crunch" into the upper right... sometimes... most of the time, mostly at the beginning of the playlist, I feel.

![Screenshot](https://cdn.pbrd.co/images/vCN9dOW6T.png)

**Comment by kilara1988** [comment]
Yeah.That happens when you use the small player view with a playlist.With the "Theater" view the play list shows fine.
I used to use a small view player with custom 720p size,but had to move to a "Theater" view because of that bug.Got used to the "Theater" view now.

On a side note if i set a custom size for a player view after i change to it from the button in the player,i can no longer change to the other view.The button stops working.Changing views works fine with default player sizes.

**Comment by Quisquose** [comment]
I'm experiencing exactly same problem.

Whenever I enable **Player > Player Size > Enable Resize** it causes the Playlist area (besides the player window) to collapse so that there's only a tiny strip of the playlist barely visible at the top of the window.

When viewing videos that are NOT part of a playlist, there's no such problem. The list of 'suggested' videos correctly displays beside the player window, and this list slides down and out of the way when the large player / cinema mode button is pressed on the player.

If I disable just the YTC Resize feature, then the Playlist goes back to displaying correctly again. 

The issue only happens for me in Firefox. In Opera I don't experience any such issue when YouTube Center's auto-resize is enabled.

**Comment by kilara1988** [comment]
I confirm that disabling Resize option fixes the playlist issue.

**Comment by Sollace** [comment]
I've got a piece of css that appears to fix the playlist issue (at least better than my first attempt, which I can't really find any more):

        .watch-small #player-playlist {
          margin-top: 0 !important;
        }
        #player-playlist .watch-playlist {
          height: 360px;
        }
        @media (min-height: 360px) {
          #player-playlist .watch-playlist {
            height: 480px;
          }
        }
        .ytcenter-resize .watch-small #player-api {
          position: absolute !important;
        }

**Comment by YePpHa** [comment]
Actually, this issue should be fixed in the latest version. Could someone verify this?

**Comment by kilara1988** [comment]
Just tested it with v546 and with the small player it is still broken(exactly like the screenshot from 1st comment).

**Comment by YePpHa** [comment]
okay

**Comment by YePpHa** [comment]
It seems to be working in Chrome. I will try to test it in Firefox.

**Comment by Sollace** [comment]
Alrighty, thanks~

**Comment by YouTubeEdge** [comment]
Ayy, just wanted to say thanks for all the activity here guys and the add-on in general.
